### PR TITLE
Make alias show output

### PR DESCRIPTION
**Pull request by deizel**
Before:

```sh-session
$ alias dockviz="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz"
$ dockviz --help
```

After:

```sh-session
$ alias dockviz="docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock nate/dockviz"
$ dockviz --help
Usage:
  dockviz [OPTIONS] <containers | help | images>

Application Options:
      --tlscacert=~/.docker/ca.pem          Trust certs signed only by this CA
      --tlscert=~/.docker/cert.pem          Path to TLS certificate file
      --tlskey=~/.docker/key.pem            Path to TLS key file
      --tlsverify                           Use TLS and verify the remote
  -H, --host=unix:///var/run/docker.sock    Docker host to connect to
  -v, --version                             Display version information.

Help Options:
  -h, --help                                Show this help message

Available commands:
  containers  Visualize docker containers.
  help        Help for dockviz.
  images      Visualize docker images.
```

### CODE REVIEW

**Comment by justone** [comment]
This is interesting.  Testing it on linux (with docker 1.9.1 and 1.10.1) and on Mac (docker 1.10.1 running in a VirtualBox VM), when I have the original alias in place (without `-it`), it always shows output, help and otherwise.

What version of docker do you run?  Is it remote or local?  What terminal program? Any special flags in the daemon configuration?

**Comment by deizel** [comment]
Hmm.. honestly, I thought `-it` was required to get output, so I've been typing it a lot.. but based on your feedback maybe there is something wrong with my setup.

Currently running locally on OS X with dlite (as opposed to docker-machine):

```sh-session
ssh docker@local.docker
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
$ cat /etc/default/docker
DOCKER_ARGS="-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 -s btrfs"
```

**Comment by justone** [comment]
Ah, nifty.  It may be a quirk of dlite.  I've been meaning to try it out, perhaps this is my motivation.

**Comment by deizel** [comment]
Well, just ping me here if you do get time/motivation to figure it out - but otherwise, feel free to close the issue if it's just me and nothing is actually broken. :wink:

**Comment by deizel** [comment]
Just a quick update.. seems related to the current implementation of dlite's reverse proxy.

Switched to bleeding edge to get https://github.com/nlf/dlite/commit/0b4fec14c4761f81b6b7df54c7bd76457b620220 but running into SSH issues now (https://github.com/nlf/dlite/commit/944c6f28677650a94870562cae90ea6382efe0a6).

Going to roll back and wait for a release as master seems to be WIP - thanks for the direction :+1:

**Pull request closed without merging**
